services:
  service1:
    restart: always
    build:
      context: ./service1
    ports:
      - "8000:8000"

  service2:
    restart: always
    build:
      context: ./service2
    ports:
      - "8001:8000"